# Generated by Django 2.1 on 2018-08-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='BlogsPost',
        ),
    ]
